## Funzzy events file
# more details see: https://github.com/cristianoliveira/funzzy
#
# list here all the events and the commands that it should execute

- name: tests
  run: "cargo test"
  change: "src/**"
  run_on_init: true
